behaviors:
  Brainfighter:
    trainer_type: ppo
    summary_freq: 5000
    time_horizon: 64
    max_steps: 500000
    keep_checkpoints: 4
    even_checkpoints: false
    checkpoint_interval: 250000
    threaded: false
    hyperparameters:
      learning_rate: 0.0003
      batch_size: 128
      buffer_size: 2048
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.2
      beta_schedule: linear
      epsilon_schedule: linear
      lambd: 0.98
      num_epoch: 3
      shared_critic: False
    network_settings:
      hidden_units: 128
      num_layers: 4
      normalize: false
      conditioning_type: none
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    self_play:
      save_steps: 40000
      team_change: 200000
      swap_steps: 10000
      playing_against_latest_model_ratio: 0.5
      window: 10
